pngs :	object-recognition-state.png person-tracking-state.png slam-state.png

object-recognition-state.png : object-recognition-state.dot
	dot object-recognition-state.dot -Tpng -oobject-recognition-state.png
person-tracking-state.png : person-tracking-state.dot
	dot person-tracking-state.dot -Tpng -operson-tracking-state.png
slam-state.png : slam-state.dot
	dot slam-state.dot -Tpng -oslam-state.png
